In [1]:
import numpy as np

In [2]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch
import torch.nn as nn

In [6]:
input = torch.tensor([3.0,2.0,-1.0])
neuron = nn.Linear(in_features=3, out_features=1)
output = neuron(input)

In [7]:
print(output)

tensor([-0.2943], grad_fn=<AddBackward0>)


In [8]:
neuron.weight

Parameter containing:
tensor([[-0.2304, -0.1489, -0.3605]], requires_grad=True)

In [9]:
neuron.bias

Parameter containing:
tensor([0.3343], requires_grad=True)

In [10]:
neuron.weight @ input.T + neuron.bias

tensor([-0.2943], grad_fn=<AddBackward0>)