In [1]:
import numpy as np
import torch.nn as nn
import torch
import pandas as pd

In [2]:
df = pd.read_csv("Prodigy University Dataset.csv")
df.head()

sat_sum  hs_gpa  fy_gpa
0      508    3.40    3.18
1      488    4.00    3.33
2      464    3.75    3.25
3      380    3.75    2.42
4      428    4.00    2.63

## Data Cleaning

In [3]:
X = df[["hs_gpa","sat_sum"]].values
y = df["fy_gpa"].values.reshape(-1,1)

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

### Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
X_train.shape

(800, 2)

### Converting to tensors

In [7]:
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

## Model

In [8]:
model = nn.Sequential(nn.Linear(2,2),#input of size 2--> hidden layer of 2 neurons
                      nn.Sigmoid(),#activation function of single hidden layer
                      nn.Linear(2,1))#output node 
                        #default activation function if not mentioned for output is linear



## Prediction

In [9]:
preds = model(X_train)
preds[:5]

tensor([[0.1158],
        [0.1191],
        [0.1277],
        [0.1487],
        [0.1040]], grad_fn=<SliceBackward0>)

In [13]:
y_train[:5]

tensor([[2.0000],
        [3.1100],
        [1.6300],
        [3.0200],
        [1.5500]])

In [12]:
criteria =  nn.MSELoss()
loss = criteria(preds, y_train)
loss

tensor(5.8211, grad_fn=<MseLossBackward0>)

In [14]:
model[0].weight

Parameter containing:
tensor([[-0.6619,  0.4169],
        [-0.1482, -0.2173]], requires_grad=True)

In [17]:
#model[1] is the activation function of the hidden layer which does not have any weights associated

In [15]:
model[2].weight

Parameter containing:
tensor([[ 0.0202, -0.5327]], requires_grad=True)

In [19]:
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr = 0.001)

In [20]:
#backward propogation
loss.backward()

In [21]:
#updating weights
optimizer.step()

In [22]:
model[0].weight

Parameter containing:
tensor([[-0.6619,  0.4169],
        [-0.1482, -0.2173]], requires_grad=True)

In [23]:
model[2].weight

Parameter containing:
tensor([[ 0.0225, -0.5308]], requires_grad=True)

In [25]:
from torch.utils.data import dataloader, TensorDataset
model = nn.Sequential(
    nn.Linear(2,2),
    nn.Sigmoid(),
    nn.Linear(2,1)
)
optimizer = optim.SGD(model.parameters(), lr = 0.001)

## performance of train and test before model training
train_loss = criteria(model(X_train), y_train)
test_loss = criteria(model(X_test),y_test)
print(f"Model without training: \n Train Loss : {train_loss:0.4f} Test Loss : {test_loss:0.4f}")

Model without training: 
 Train Loss : 8.8763 Test Loss : 9.1768


In [26]:
##Look at predictions
model(X_train)[:5]

tensor([[-0.3704],
        [-0.3710],
        [-0.3510],
        [-0.4180],
        [-0.3157]], grad_fn=<SliceBackward0>)