In [1]:
import numpy as np

In [3]:
# %pip install torch

In [4]:
import torch
import torch.nn as nn

In [5]:
input = torch.tensor([3.0,2.0,-1.0])
neuron = nn.Linear(in_features=3, out_features=1)
output = neuron(input)

In [6]:
print(output)

tensor([0.7099], grad_fn=<AddBackward0>)


In [7]:
neuron.weight

Parameter containing:
tensor([[-0.0033,  0.4655,  0.3002]], requires_grad=True)

In [8]:
neuron.bias

Parameter containing:
tensor([0.0889], requires_grad=True)

In [9]:
neuron.weight @ input.T + neuron.bias

C:\Users\scientist-ns\AppData\Local\Temp\ipykernel_20756\4240275390.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3575.)
  neuron.weight @ input.T + neuron.bias


tensor([0.7099], grad_fn=<AddBackward0>)